# Generated by Django 5.2.7 on 2025-10-27 00:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('damage_description', models.TextField(blank=True)),
                ('diseases_caused', models.JSONField(blank=True, default=list)),
                ('pesticide_recommendations', models.TextField(blank=True)),
                ('biological_control', models.TextField(blank=True)),
                ('cultural_control', models.TextField(blank=True)),
                ('confidence_threshold', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('yolo', 'YOLO'), ('resnet', 'ResNet'), ('custom', 'Custom')], default='yolo', max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed'), ('active', 'Active'), ('archived', 'Archived')], default='training', max_length=20)),
                ('model_file', models.FileField(blank=True, upload_to='models/pest_detection/')),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('training_dataset', models.CharField(blank=True, max_length=200)),
                ('training_epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=8)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('map50', models.FloatField(blank=True, null=True)),
                ('map95', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pest_types', models.ManyToManyField(blank=True, to='pest_detection.pesttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('confidence_threshold', models.FloatField(default=0.25)),
                ('iou_threshold', models.FloatField(default=0.5)),
                ('image_size', models.IntegerField(default=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pest_detection.detectionmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PestDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('image_name', models.CharField(max_length=255)),
                ('image_size_width', models.IntegerField()),
                ('image_size_height', models.IntegerField()),
                ('total_pests_detected', models.IntegerField(default=0)),
                ('detection_results', models.JSONField(default=dict)),
                ('raw_detections', models.JSONField(blank=True, default=list)),
                ('inference_time_ms', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('farm_location', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='pest_detection.detectionsession')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correct', 'Correct Detection'), ('incorrect', 'Incorrect Detection'), ('missed', 'Missed Detection'), ('false_positive', 'False Positive')], max_length=20)),
                ('corrected_count', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pest_detection.pestdetection')),
                ('pest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest_detection.pesttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('confidence_avg', models.FloatField(blank=True, null=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_counts', to='pest_detection.pestdetection')),
                ('pest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest_detection.pesttype')),
            ],
            options={
                'ordering': ['pest_type__name'],
                'unique_together': {('detection', 'pest_type')},
            },
        ),
        migrations.CreateModel(
            name='DetectionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_detections', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(blank=True, null=True)),
                ('locations_count', models.IntegerField(default=0)),
                ('most_affected_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest_detection.pesttype')),
            ],
            options={
                'ordering': ['-date', 'pest_type__name'],
                'unique_together': {('date', 'pest_type')},
            },
        ),
    ]
